from pathlib import Path

import numpy as np
from PIL import Image


# =========================================================
# SETTINGS
# =========================================================

THRESHOLDS = [
    0.30,
    0.35,
    0.40,
    0.45,
    0.50,
    0.55
]

PAIR_COUNT = 5


# =========================================================
# STORE FINAL RESULTS
# =========================================================

threshold_results = []


# =========================================================
# TEST EACH THRESHOLD
# =========================================================

for threshold in THRESHOLDS:

    print(
        f"\n\n========== THRESHOLD {threshold:.2f} =========="
    )

    pair_ious = []
    pair_f1s = []

    for i in range(1, PAIR_COUNT + 1):

        pair = f"pair_{i:02d}"

        # Probability map generated by robust model
        probability_path = Path(
            f"integration_data/"
            f"robust_{pair}/"
            f"change_probability.png"
        )

        # Ground truth
        ground_truth_path = Path(
            f"dataset/change/"
            f"{pair}/mask.png"
        )

        if not probability_path.exists():
            raise FileNotFoundError(
                f"Probability map missing: {probability_path}"
            )

        if not ground_truth_path.exists():
            raise FileNotFoundError(
                f"Ground truth missing: {ground_truth_path}"
            )

        # -------------------------------------------------
        # LOAD PROBABILITY MAP
        # -------------------------------------------------

        probability_img = Image.open(
            probability_path
        ).convert("L")

        probability = (
            np.array(
                probability_img,
                dtype=np.float32
            ) / 255.0
        )

        # Apply current threshold
        pred = probability >= threshold

        # -------------------------------------------------
        # LOAD GROUND TRUTH
        # -------------------------------------------------

        gt_img = Image.open(
            ground_truth_path
        ).convert("L")

        if gt_img.size != probability_img.size:

            gt_img = gt_img.resize(
                probability_img.size,
                Image.Resampling.NEAREST
            )

        gt = np.array(gt_img) > 127

        # -------------------------------------------------
        # METRICS
        # -------------------------------------------------

        tp = np.logical_and(
            pred,
            gt
        ).sum()

        fp = np.logical_and(
            pred,
            np.logical_not(gt)
        ).sum()

        fn = np.logical_and(
            np.logical_not(pred),
            gt
        ).sum()

        intersection = tp

        union = np.logical_or(
            pred,
            gt
        ).sum()

        iou = (
            intersection / union
            if union > 0
            else 0
        )

        precision = (
            tp / (tp + fp)
            if (tp + fp) > 0
            else 0
        )

        recall = (
            tp / (tp + fn)
            if (tp + fn) > 0
            else 0
        )

        f1 = (
            2 * precision * recall /
            (precision + recall)
            if (precision + recall) > 0
            else 0
        )

        actual_change = (
            gt.mean() * 100
        )

        predicted_change = (
            pred.mean() * 100
        )

        pair_ious.append(iou)
        pair_f1s.append(f1)

        print(
            f"{pair} | "
            f"IoU: {iou:.4f} | "
            f"F1: {f1:.4f} | "
            f"Precision: {precision:.4f} | "
            f"Recall: {recall:.4f} | "
            f"Actual: {actual_change:.2f}% | "
            f"Predicted: {predicted_change:.2f}%"
        )

    # =====================================================
    # THRESHOLD SUMMARY
    # =====================================================

    average_iou = float(
        np.mean(pair_ious)
    )

    worst_iou = float(
        np.min(pair_ious)
    )

    average_f1 = float(
        np.mean(pair_f1s)
    )

    threshold_results.append({
        "threshold": threshold,
        "average_iou": average_iou,
        "worst_iou": worst_iou,
        "average_f1": average_f1
    })

    print(
        f"\nAverage IoU: {average_iou:.4f}"
    )

    print(
        f"Worst Pair IoU: {worst_iou:.4f}"
    )

    print(
        f"Average F1: {average_f1:.4f}"
    )


# =========================================================
# FINAL COMPARISON
# =========================================================

print(
    "\n\n"
    "=============== FINAL THRESHOLD COMPARISON ==============="
)

for result in threshold_results:

    print(
        f"Threshold {result['threshold']:.2f} | "
        f"Average IoU: {result['average_iou']:.4f} | "
        f"Worst IoU: {result['worst_iou']:.4f} | "
        f"Average F1: {result['average_f1']:.4f}"
    )


# =========================================================
# BEST THRESHOLD
# =========================================================

best = max(
    threshold_results,
    key=lambda x: x["average_iou"]
)

print(
    "\n================ BEST THRESHOLD ================"
)

print(
    f"Threshold: {best['threshold']:.2f}"
)

print(
    f"Average IoU: {best['average_iou']:.4f}"
)

print(
    f"Worst Pair IoU: {best['worst_iou']:.4f}"
)

print(
    f"Average F1: {best['average_f1']:.4f}"
)

print(
    "================================================"
)